alias: Pause Music
description: ""
triggers:
  - trigger: conversation
    command:
      - pause
conditions: []
actions:
  - action: script.extract_media_player
    metadata: {}
    response_variable: mediaplayer
    data:
      triggering_device_id: "{{trigger.user_input.device_id}}"
  - action: media_player.media_pause
    target:
      entity_id: "{{ mediaplayer.mediaplayer }}"
  - set_conversation_response: Previous song.
mode: single
