alias: Stop song
description: ""
triggers:
  - trigger: conversation
    command:
      - stop
conditions: []
actions:
  - action: script.extract_media_player
    metadata: {}
    response_variable: mediaplayer
    data:
      triggering_device_id: "{{trigger.user_input.device_id}}"
  - action: media_player.media_stop
    target:
      entity_id: "{{ mediaplayer.mediaplayer }}"
  - set_conversation_response: Stopped playback
mode: single
